//OLD DATABSE CASE
//Superseded by TaskDB
//DO NOT EDIT!!!






import java.sql.*;

public class TaskDatabase {
    private static Connection con;
    private static boolean hasData = false;

    public TaskDatabase() {

    }

    public ResultSet displayUsers() throws SQLException, ClassNotFoundException {
        if(con == null){
            getConnection();
        }

        Statement state = null;
        try {
            state = con.createStatement();
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
        ResultSet res = state.executeQuery("SELECT taskName, taskDescription, startDate, endDate FROM task");
        return res;
    }

    private void getConnection() throws ClassNotFoundException, SQLException {
        Class.forName("org.sqlite.JDBC");  //sets up JDBC driver in the driver manager
        con = DriverManager.getConnection("jdbc:sqlite:TaskDBTest.db");
        initialise();
    }

    private void initialise() throws SQLException {
        if(!hasData){ //if hasData is false
            hasData = true;

            Statement state = con.createStatement();
            ResultSet res = state.executeQuery("SELECT name FROM sqlite_master WHERE type='table' AND name='task'");
            //sql_master is the master table in a sqlite data
            //it keeps a record of all tables.
            //This tells us if there are any tables with the name user. If there are, it will use that one.

            if(!res.next()){
                System.out.println("Building the User table with prepopulated values");
                //need to build table
                Statement state2 = con.createStatement();
                //state2.execute("CREATE TABLE user(id integer, "+"fName varchar(60)," + "lName varchar(60)," + "primary key(id));");
                state2.execute("CREATE TABLE task(id integer, "+"taskName varchar(60),"+"taskDescription varchar(240),"+"startDate DATE,"+"endDate DATE,"+"primary key(id));");

                //inserting some sample data
                /*PreparedStatement prep = con.prepareStatement("INSERT INTO user values(?,?,?);");
                //column 1 = primary key - autogenerated
                prep.setString(2, "John"); //column 2 = firstname
                prep.setString(3, "McGinn");// column 3 = last name
                prep.execute();

                PreparedStatement prep2 = con.prepareStatement("INSERT INTO user values(?,?,?);");
                prep2.setString(2, "Babatunde"); //column 2 = firstname
                prep2.setString(3, "Ogunde");// column 3 = last name
                prep2.execute();*/

                //Trying to insert a task
                PreparedStatement prep3 = con.prepareStatement("INSERT INTO task values(?,?,?,?,?);");
                prep3.setString(2, "First"); //column 2 = firstname
                prep3.setString(3, "This is a task");
                prep3.setString(4, "2020-02-09");// column 3 = last name
                prep3.setString(5, "2020-02-11");
                prep3.execute();

            }
        }
    }

    public void addUser(String firstname, String lastname) throws SQLException, ClassNotFoundException {
        if(con == null){
            getConnection();
        }

        PreparedStatement prep = con.prepareStatement("INSERT INTO user values(?,?,?);");
        prep.setString(2, firstname);
        prep.setString(3, lastname);
        prep.execute();
    }
}
